# Generated by Django 2.1.4 on 2018-12-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='user_id',
            new_name='user',
        ),
    ]
