# Generated by Django 2.1.4 on 2018-12-31 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Banks'),
        ),
    ]
